# --- OSD / czas / precyzja ---
osd-level=3
osd-fractions=yes

# --- Sterowanie czasem i seek ---
hr-seek=yes
hr-seek-framedrop=no

# --- Wygląd OSD ---
osd-font-size=28
osd-duration=2000

# --- Wideo ---
video-sync=display-resample
interpolation=no

# --- Audio (bez zmian jakości) ---
audio-normalize-downmix=no

# --- Ogólne ---
keep-open=yes
pause=no

